site_name: Flexible DQM Manual
theme:
  name: 'material' 

nav:
  - Home: index.md
  - Software Overview: software.md
  - Technology Stack Overview: tech_stack.md
  - Environment: environment.md
  - Installing the DQM Components: install.md
  - Running the DQM Components: run.md
  - Configuring the DQM components: configure.md
  - Miscellaneous: miscellaneous.md

plugins:
  - search
  - with-pdf:
  - git-revision-date-localized:
      enable_creation_date: false
  - print-site

markdown_extensions:
  - attr_list

extra_css:
- 'css/extra.css'
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css